### PR TITLE
Enable crop to roi

### PR DESCRIPTION
**Pull request by vsuryamurthy**

### CODE REVIEW

**Comment by hgaiser** [comment]
Is dr_ensenso not yet released? I'm asking because the CI fails ^^

**Comment by vsuryamurthy** [comment]
It is released but I know not why dr_ensenso_node fails

**Comment by hgaiser** [comment]
@ekrikelis can you have a look ? If you're too busy, let me know and I'll have a look.

**Comment by vsuryamurthy** [comment]
dr_ensenso also doesnt build cos of missing unit tests.

**Comment by hgaiser** [comment]
Yeah but that's a different issue ^^

**Comment by vsuryamurthy** [comment]
Okay, I thought it was related cos I cannot find the latest version in repos/rolling/latest

**Comment by hgaiser** [comment]
Oh maybe it's just rolling that needs to be updated, lets check..

**Comment by hgaiser** [comment]
That fixed it :) It still has no unit test so it doesn't pass CI, but that's a different issue.

**Pull request merged**
